// Code generated by protoc-gen-go-grpc stub. DO NOT EDIT.
// Bu dosya geçici bir stub'dır. Backend developer proto'yu implement edecek.
// Gerçek üretim kodu: protoc ile api/proto/reservation.proto'dan üretilmeli.

package reservationv1

import (
	"context"

	"google.golang.org/grpc"
)

// ── Messages ─────────────────────────────────────────────────────────────────

type ReserveSeatRequest struct {
	UserId         string
	TripId         string
	SeatId         string
	IdempotencyKey string
}

type ReserveSeatResponse struct {
	Success bool
	Message string
}

// ── Client Interface ─────────────────────────────────────────────────────────

type ReservationServiceClient interface {
	ReserveSeat(ctx context.Context, in *ReserveSeatRequest, opts ...grpc.CallOption) (*ReserveSeatResponse, error)
}

type reservationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReservationServiceClient(cc grpc.ClientConnInterface) ReservationServiceClient {
	return &reservationServiceClient{cc}
}

func (c *reservationServiceClient) ReserveSeat(ctx context.Context, in *ReserveSeatRequest, opts ...grpc.CallOption) (*ReserveSeatResponse, error) {
	out := new(ReserveSeatResponse)
	err := c.cc.Invoke(ctx, "/reservation.v1.ReservationService/ReserveSeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
